nv-auto-deploy/TensorRT-LLM

- examples/auto_deploy/.vscode/launch.json
- examples/auto_deploy/.vscode/settings.json
- examples/auto_deploy/README.md
- examples/auto_deploy/simple_config.py
- tensorrt_llm/_torch/auto_deploy/models/factory.py
- tensorrt_llm/_torch/auto_deploy/models/hf.py
- tensorrt_llm/_torch/auto_deploy/shim/demollm.py
- tensorrt_llm/_torch/auto_deploy/shim/interface.py
- tensorrt_llm/_torch/auto_deploy/transformations/transform.py
- tests/unittest/_torch/auto_deploy/unit/singlegpu/models/test_hf.py
cherry-picking https://github.com/NVIDIA/TensorRT-LLM/pull/4371
> [AutoDeploy] HF factory improvements (#4371)

- tensorrt_llm/_torch/auto_deploy/distributed/common.py
- tensorrt_llm/_torch/auto_deploy/shim/ad_executor.py
- tensorrt_llm/_torch/auto_deploy/transformations/library/sharding.py
- tensorrt_llm/_torch/auto_deploy/transformations/transform.py
- tests/unittest/_torch/auto_deploy/unit/multigpu/transformations/library/test_bmm_sharding.py
see https://github.com/NVIDIA/TensorRT-LLM/pull/4368
> [AutoDeploy] bmm sharder

- tensorrt_llm/_torch/auto_deploy/shim/ad_executor.py
> [AutoDeploy] no need for cleanup in ADExecutor

- examples/auto_deploy/simple_config.py
- tensorrt_llm/_torch/auto_deploy/custom_ops/torch_attention.py
- tensorrt_llm/_torch/auto_deploy/custom_ops/triton_attention.py
- tensorrt_llm/_torch/auto_deploy/models/deepseek.py
- tensorrt_llm/_torch/auto_deploy/transformations/_graph.py
- tests/unittest/_torch/auto_deploy/integration/test_ad_build.py
- tests/unittest/_torch/auto_deploy/unit/multigpu/test_ad_build_small_multi.py
- tests/unittest/_torch/auto_deploy/unit/singlegpu/test_ad_build_small_single.py
Changes in [https://github.com/NVIDIA/TensorRT-LLM/pull/4281](https://github.com/NVIDIA/TensorRT-LLM/pull/4281) to fix DSV3/DSR1/DSV2-Lite related support
> Deepseek support + fixes

- examples/auto_deploy/build_and_run_ad.py
- tensorrt_llm/_torch/auto_deploy/custom_ops/attention_interface.py
- tensorrt_llm/_torch/auto_deploy/custom_ops/flashinfer_attention.py
see issues mentioned in the diff
> [AutoDeploy] WAR to address max_batch_size,max_seq_len flashinfer issue

- examples/auto_deploy/README.md
- tensorrt_llm/_torch/auto_deploy/models/phi.py
- tensorrt_llm/_torch/auto_deploy/transformations/library/fusion.py
- tensorrt_llm/_torch/auto_deploy/utils/node_utils.py
> Add Phi3.5-mini patch and revert gemm_fusion change

- examples/auto_deploy/README.md
- tensorrt_llm/_torch/auto_deploy/models/phi.py
- tensorrt_llm/_torch/auto_deploy/transformations/library/fusion.py
- tensorrt_llm/_torch/auto_deploy/utils/node_utils.py
> Add Phi3.5-mini patch and revert gemm_fusion change (rebased)

- tensorrt_llm/_torch/auto_deploy/models/factory.py
fixing dtype for random initialization
> [AutoDeploy] correct random init

- examples/auto_deploy/README.md
- examples/auto_deploy/simple_config.py
- tensorrt_llm/_torch/auto_deploy/custom_ops/attention_interface.py
- tensorrt_llm/_torch/auto_deploy/custom_ops/flashinfer_attention.py
- tensorrt_llm/_torch/auto_deploy/custom_ops/triton_attention.py
- tensorrt_llm/_torch/auto_deploy/models/factory.py
- tensorrt_llm/_torch/auto_deploy/models/hf.py
- tensorrt_llm/_torch/auto_deploy/models/phi.py
- tensorrt_llm/_torch/auto_deploy/shim/interface.py
- tensorrt_llm/_torch/auto_deploy/transformations/export.py
- tensorrt_llm/_torch/auto_deploy/transformations/library/attention.py
- tensorrt_llm/_torch/auto_deploy/transformations/library/fusion.py
- tensorrt_llm/_torch/auto_deploy/transformations/library/kvcache.py
- tensorrt_llm/_torch/auto_deploy/transformations/library/rope.py
- tensorrt_llm/_torch/auto_deploy/transformations/transform.py
- tensorrt_llm/_torch/auto_deploy/utils/node_utils.py
- tests/unittest/_torch/auto_deploy/integration/test_ad_build.py
- tests/unittest/_torch/auto_deploy/unit/multigpu/test_ad_build_small_multi.py
- tests/unittest/_torch/auto_deploy/unit/singlegpu/test_ad_build_small_single.py
- tests/unittest/_torch/auto_deploy/unit/singlegpu/transformations/library/test_kv_cache.py
> [Autodeploy] Llama4, dropout improved, shape_prop, attn i/f, phi 3.5

- tensorrt_llm/_torch/auto_deploy/models/hf.py
> set trust_remote_code to true for autotokenizer when customize_tokenizer=True

- tensorrt_llm/_torch/auto_deploy/transformations/library/rope.py
Fix for Llama4 failure
Also apply extract_op_args to other rope transformations
<details>
`run  [--disable-fail-fast --skip-test --stage-list "A10-1, xxx" --gpu-type "A30, …
> Fix RoPE args extraction

- tensorrt_llm/_torch/auto_deploy/models/hf.py
- tensorrt_llm/_torch/auto_deploy/transformations/library/rope.py
- tensorrt_llm/_torch/auto_deploy/transformations/library/sharding.py
- tensorrt_llm/_torch/auto_deploy/transformations/transform.py
- tensorrt_llm/_torch/auto_deploy/utils/node_utils.py
see individual PRs for description
> [AutoDeploy] Merge Staging branch for 05/23 and 05/24

- tensorrt_llm/_torch/auto_deploy/custom_ops/triton_kernels/attention_with_kv_cache.py
Ensure the attn values that are invalid are masked before computing max_attn
> Fix garbage output issue with TritonWithFlattenedInputs attention backend

- tensorrt_llm/_torch/auto_deploy/shim/interface.py
- tensorrt_llm/_torch/auto_deploy/transformations/library/attention.py
- tensorrt_llm/_torch/auto_deploy/transformations/library/collectives.py
- tensorrt_llm/_torch/auto_deploy/transformations/library/eliminate_redundant_transposes.py
- tensorrt_llm/_torch/auto_deploy/transformations/library/ep_sharding.py
- tensorrt_llm/_torch/auto_deploy/transformations/library/fused_moe.py
- tensorrt_llm/_torch/auto_deploy/transformations/library/kvcache.py
- tensorrt_llm/_torch/auto_deploy/transformations/library/quantization.py
- tensorrt_llm/_torch/auto_deploy/transformations/library/rope.py
- tensorrt_llm/_torch/auto_deploy/transformations/library/sharding.py
- tensorrt_llm/_torch/auto_deploy/transformations/transform.py
> [AutoDeploy] transformation logging and disabled fuse_moe

- tensorrt_llm/_torch/auto_deploy/custom_ops/_triton_attention_internal.py
> fix triton unit tests

- examples/auto_deploy/.vscode/settings.json
- tensorrt_llm/_torch/auto_deploy/models/__init__.py
- tensorrt_llm/_torch/auto_deploy/models/mixtral.py
- tensorrt_llm/_torch/auto_deploy/transformations/export.py
- tests/unittest/_torch/auto_deploy/_utils_test/_model_test_utils.py
- tests/unittest/_torch/auto_deploy/unit/singlegpu/test_ad_build_small_single.py
upgrading our usage of transformers to get ready to upgrade transformers from 4.51 --> 4.53
> [AutoDeploy] get AD ready for transformers 4.53.0

- benchmarks/cpp/prepare_dataset.py
- benchmarks/cpp/utils/prepare_real_data.py
- benchmarks/cpp/utils/prepare_synthetic_data.py
- tests/unittest/_torch/auto_deploy/unit/singlegpu/test_ad_trtllm_bench.py
Reverts nv-auto-deploy/TensorRT-LLM#76
> Revert "Fix AD trtllm-bench integration test and enable trtllm-bench integration "

- tensorrt_llm/_torch/auto_deploy/transform/interface.py
Handle gm info updates based on previous `is_clean` and `has_valid_shape` states.
- Unit tests passed;
- Tested on TRT-bench : https://docs.google.com/document/d/19uckwXP5rTIRsifLnFuvgWThvQhubllLNYRhiLzO7xE/edit?usp=sharing
<details>
`run  [--reuse-test (optional)pipeline-id --disable-fail-fast --skip-test --stage-list "A10-PyTorch-1, xxx" --gpu-type "A30, H100_PCIe" --test-backend "pytorch, cpp" --add-multi-gpu-test --only-multi-gpu-test --disable-multi-gpu-test --post-merge --extra-stage "H100_PCIe-TensorRT-Post-Merge-1, xxx" …
> improve error handling and graph clean-up

- tensorrt_llm/_torch/auto_deploy/transformations/library/attention.py
Source code for llama4 eager attention for text model:
https://github.com/huggingface/transformers/blob/main/src/transformers/models/llama4/modeling_llama4.py#L223
Tested with:
```
python build_and_run_ad.py \
--model "meta-llama/Llama-4-Scout-17B-16E" \
--args.world-size 1 \
--args.compile-backend "torch-simple" \
--args.attn-backend "triton" \
--args.model_factory "AutoModelForImageTextToText" \
--args.runtime "demollm" \
--args.skip-loading-weights True \
--benchmark.enabled False --args.model-kwargs.text_config.num_hidden_layers 2 \
--args.model-kwargs.vision_config.num_hidden_layers 2
```
Run `/bot [-h|--help]` to print this …
> fix: pattern match Llama 4 eager attention

- tensorrt_llm/_torch/auto_deploy/transformations/library/rope.py
For the bug discussed in https://github.com/NVIDIA/TensorRT-LLM/issues/4311
Tested with:
```
python build_and_run_ad.py \
--model "meta-llama/Llama-4-Scout-17B-16E" \
--args.world-size 1 \
--args.compile-backend "torch-simple" \
--args.attn-backend "triton" \
--args.model_factory "AutoModelForImageTextToText" \
--args.runtime "demollm" \
--args.skip-loading-weights True \
--benchmark.enabled False --args.model-kwargs.text_config.num_hidden_layers 2 \
--args.model-kwargs.vision_config.num_hidden_layers 2
```
<details>
`run  [--disable-fail-fast --skip-test …
> Fix meta-llama/Llama-4-Scout-17B-16E Rope Pattern Match

- tensorrt_llm/_torch/auto_deploy/custom_ops/attention_interface.py
- tensorrt_llm/_torch/auto_deploy/shim/ad_executor.py
- tensorrt_llm/_torch/auto_deploy/shim/interface.py
- tensorrt_llm/_torch/auto_deploy/transform/library/cleanup_input_constraints.py
- tensorrt_llm/_torch/auto_deploy/transform/library/kvcache.py
cherry-picked from https://github.com/NVIDIA/TensorRT-LLM/pull/8002
> [https://nvbugs/5527956][fix] AutoDeploy: fix IMA due to outdated metadata

- tests/unittest/_torch/auto_deploy/unit/singlegpu/test_ad_build_small_single.py
> unit test for free_mem_ratio

- tests/unittest/_torch/auto_deploy/unit/singlegpu/shim/test_engine.py
> adjust test_engine seed to new sampling seed
