examples/auto_deploy/simple_config.py, tensorrt_llm/_torch/auto_deploy/transformations/library/kvcache.py, tensorrt_llm/_torch/auto_deploy/transformations/transform.py
avoid cache resize if not necessary. We have seen failure cases where cache resize may cause illegal memory access
=> [AutoDeploy] set default cache resize portion to 0.0

tensorrt_llm/_torch/auto_deploy/shim/ad_executor.py
Make sure device id is always set. It seems that the HF device_map doesn't respect default device id when the device passed in is just "cuda"
=> [AutoDeploy] ensure device id is in our device setting

examples/auto_deploy/build_and_run_ad.py
skip simple benchmarking for trtllm runtime since it is unreliable
=> skipping benchmarking for trtllm runtime

tensorrt_llm/_torch/auto_deploy/custom_ops/attention_interface.py, tensorrt_llm/_torch/auto_deploy/shim/interface.py, tensorrt_llm/_torch/auto_deploy/transformations/library/kvcache.py, tensorrt_llm/_torch/auto_deploy/transformations/transform.py, tests/unittest/_torch/auto_deploy/unit/singlegpu/transformations/library/test_kv_cache.py
supersedes and closes [#4369](https://github.com/NVIDIA/TensorRT-LLM/pull/4369) (was already reviewed and approved)
=> [AutoDeploy] more robust handling of attention interface and input nodes

tensorrt_llm/_torch/auto_deploy/custom_ops/flashinfer_attention.py, tensorrt_llm/_torch/auto_deploy/custom_ops/triton_attention.py, tensorrt_llm/_torch/auto_deploy/transformations/export.py, tensorrt_llm/_torch/auto_deploy/transformations/library/rope.py, tensorrt_llm/_torch/auto_deploy/transformations/transform.py, tensorrt_llm/_torch/auto_deploy/utils/node_utils.py
1. Patch torch.ops.linear.simple to always gets bias arg in export pipeline
Fix for the failure:
```
RuntimeError: linear::simple() is missing value for argument 'bias'. Declaration: linear::simple(Tensor input, Tensor weight, Tensor? bias) -> Tensor
```
for granite moe models/ apple models
2. Lift the state_dict canonicalize_graph with shape prop to meta device, since shape propagation does same device check for ops like aten.mul
3. Update args extraction logic of attention custom op: able to extract from kwargs and get default value from op schema …
=> Several Bug Fix: bias missing for linear/lift canonicalize_graph to meta device/enhance attention op args extraction

tensorrt_llm/_torch/auto_deploy/transformations/library/attention.py
In some cases, during torch export default values are not captured in the graph (one case is when we set all default values for kwargs). This breaks the auto deploy pipeline as `match_causal_attn_mask()` sets these values to None. Updated logic to set values to default if not provided to the node.
=> Fix for attention argument dropout_p='None' 

examples/auto_deploy/README.md, examples/auto_deploy/simple_config.py, tensorrt_llm/_torch/auto_deploy/models/hf.py, tensorrt_llm/_torch/auto_deploy/transformations/library/rope.py, tensorrt_llm/_torch/auto_deploy/utils/node_utils.py, tests/unittest/_torch/auto_deploy/integration/test_ad_build.py, tests/unittest/_torch/auto_deploy/unit/multigpu/test_ad_build_small_multi.py, tests/unittest/_torch/auto_deploy/unit/singlegpu/test_ad_build_small_single.py
see https://github.com/NVIDIA/TensorRT-LLM/pull/4163
=> [AutoDeploy] Llama-4 support + AutoModelForImageTextToText

tensorrt_llm/_torch/auto_deploy/transformations/library/sharding.py, tensorrt_llm/_torch/auto_deploy/utils/node_utils.py
Granite Model family MoEs are stored in shape [num_experts, output_size, input_size] and calculated in this way:
```
def forward(self, inputs, expert_size):
"""
Forward pass of the GraniteMoeParallelExperts module.
Args:
inputs (Tensor):
Input tensor.
expert_size:
Expert size information.
Returns:
Tensor: Output tensor.
"""
input_list = inputs.split(expert_size, dim=0)
output_list = []
for i in range(self.num_experts):
output_list.append(F.linear(input_list[i], self.weight[i]))
results = torch.cat(output_list, dim=0)
return results
```
Currently MoE weights are not sharded or supported by our pattern matcher.
This update is for the TP sharder to recognize this case and skip sharding the weight.
[JIRA ticket link/nvbug link/github issue …
=> fix sharding for Granite MoE, skip simple shard for MoE weights

examples/auto_deploy/build_and_run_ad.py, examples/auto_deploy/simple_config.py, tensorrt_llm/_torch/auto_deploy/models/factory.py, tensorrt_llm/_torch/auto_deploy/models/hf.py, tests/unittest/_torch/auto_deploy/unit/singlegpu/models/test_hf.py
Test command:
```
python build_and_run_ad.py --config '{"world_size":1, "model":"apple/OpenELM-3B-Instruct", "attn_backend":"FlashInfer", "compile_backend":"torch-compile", "benchmark": false,"customize_tokenizer":true, "tokenizer_name":"meta-llama/Llama-2-7b-hf"}'  --model-kwargs '{}' 
```
Need to set both `customize_tokenizer` and `tokenizer_name`,
model list:
```
apple/OpenELM-3B-Instruct
apple/OpenELM-1_1B-Instruct
apple/OpenELM-270M-Instruct
apple/OpenELM-450M-Instruct
```
Prompt output is still not coherent after loading the tokenzier, e.g.
```
[05/27/2025-21:44:46] [TRT-LLM AUTO-DEPLOY] [I] [PROMPT 0] How big is the universe? : 1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
[05/27/2025-21:44:46] [TRT-LLM AUTO-DEPLOY] [I] [PROMPT …
```
=> Support loading other model's tokenizer for apple models

tensorrt_llm/_torch/auto_deploy/shim/ad_executor.py, tensorrt_llm/_torch/auto_deploy/shim/demollm.py
For https://github.com/NVIDIA/TensorRT-LLM/issues/4841 and https://github.com/NVIDIA/TensorRT-LLM/issues/5254
<details>
`run  [--disable-fail-fast --skip-test --stage-list "A10-1, xxx" --gpu-type "A30, H100_PCIe" --add-multi-gpu-test --only-multi-gpu-test --disable-multi-gpu-test --post-merge --extra-stage "H100_PCIe-[Post-Merge]-1, xxx"]`
Launch build/test pipelines. All previously running jobs will be killed.
`--disable-fail-fast ` *(OPTIONAL)* : Disable fail fast on build/tests/infra failures.
`--skip-test ` *(OPTIONAL)* : Skip all test stages, but still …
=> Fix bad output issue for demollm and trtllm

tensorrt_llm/_torch/auto_deploy/shim/demollm.py, tests/unittest/_torch/auto_deploy/unit/singlegpu/shim/test_engine.py
1. update DemoEngine to handle case `sampling_params.top_k=None`, will run greedy search if `sampling_params.top_k=None`. The default value is 200. Added an unit test for the sampler.
**NOTE**:
We can enable trtllm runtime with topk sampling using `--args.mixed-sampler True` in the new config system.
Passes unit tests and `test_ad_build.py`, didn't test `test_lm_eval.py`
<details>
`run  [--disable-fail-fast --skip-test --stage-list "A10-1, xxx" --gpu-type "A30, H100_PCIe" --add-multi-gpu-test --only-multi-gpu-test --disable-multi-gpu-test --post-merge …
=> Fix `sampling_params.top_k is None` issue for demollm

requirements.txt, tensorrt_llm/_torch/auto_deploy/utils/_config.py, tests/unittest/_torch/auto_deploy/unit/singlegpu/utils/test_config.py
This PR introduces a utility (as a mix-in class) to dynamically merge yaml config files into pydantic base settings (our config system in TRT-LLM). 
For now, it's only used in the accompanying unit test but I anticipate this to the main mechanism to configure our modular `InferenceOptimizer` (i.e. a custom InferenceOptimizer = default class + custom yaml config).
Other argument sources (like CLI arguments), default values, and init values are still valid as well of course
=> [AutoDeploy] yaml config loader for dynamic settings (closes #4366)

examples/auto_deploy/README.md, examples/auto_deploy/build_and_run_ad.py, tensorrt_llm/_torch/auto_deploy/llm_args.py, tensorrt_llm/_torch/auto_deploy/shim/ad_executor.py, tensorrt_llm/_torch/auto_deploy/transformations/library/kvcache.py, tensorrt_llm/_torch/auto_deploy/transformations/transform.py, tests/unittest/_torch/auto_deploy/unit/singlegpu/shim/test_llm_config.py, tests/unittest/_torch/auto_deploy/unit/singlegpu/test_ad_build_small_single.py
This PR refines AD configurability in the following ways
New CLI options with reduced configurability:
```bash
✗ python build_and_run_ad.py --help                                      
usage: build_and_run_ad.py [-h] [--args [JSON]] [--args.model {str,Path}] [--args.model-factory {AutoModelForCausalLM,AutoModelForImageTextToText}] [--args.model-kwargs Dict[str,Any]] [--args.skip-loading-weights bool]
[--args.checkpoint-device {str,null}] [--args.tokenizer {str,Path,null}] [--args.tokenizer-kwargs Dict[str,Any]] [--args.skip-tokenizer-init bool] [--args.disable-overlap-scheduler bool]
[--args.mixed-sampler bool] [--args.world-size int] [--args.runtime {demollm,trtllm}] [--args.device str] [--args.kv-cache-dtype str] [--args.attn-backend {flashinfer,triton}]
[--args.mla-backend …
```
=> [AutoDeploy] Refining AD configurability

tensorrt_llm/_torch/auto_deploy/custom_ops/torch_moe.py, tensorrt_llm/_torch/auto_deploy/models/hf.py, tensorrt_llm/_torch/auto_deploy/transformations/_graph.py, tensorrt_llm/_torch/auto_deploy/transformations/library/__init__.py, tensorrt_llm/_torch/auto_deploy/transformations/library/ep_sharding.py, tensorrt_llm/_torch/auto_deploy/transformations/library/fused_moe.py, tensorrt_llm/_torch/auto_deploy/transformations/library/quantization.py, tensorrt_llm/_torch/auto_deploy/transformations/library/quantize_moe.py, tensorrt_llm/_torch/auto_deploy/transformations/transform.py, tensorrt_llm/_torch/auto_deploy/utils/node_utils.py, tensorrt_llm/_torch/auto_deploy/utils/quantization_utils.py, tests/unittest/_torch/auto_deploy/_utils_test/_model_test_utils.py, tests/unittest/_torch/auto_deploy/unit/singlegpu/custom_ops/test_ad_moe_op.py, tests/unittest/_torch/auto_deploy/unit/singlegpu/transformations/library/test_moe_fusion.py, tests/unittest/_torch/auto_deploy/unit/singlegpu/transformations/library/test_quant_moe.py
Separate from https://github.com/NVIDIA/TensorRT-LLM/pull/4361
Tested e2e with `nvidia/Mixtral-8x7B-Instruct-v0.1-FP8` and `nvidia/Mixtral-8x7B-Instruct-v0.1-FP4` on B100, works with both world_size=1 and world_size=2
Note that the Mixtral models are now in patched moe path after the patch in [qwen3.py](https://github.com/nv-auto-deploy/TensorRT-LLM/blob/feat/ad-2025-07-07/tensorrt_llm/_torch/auto_deploy/models/qwen3.py)
`nvidia/DeepSeek-R1-FP4` only work with `full_state_dict` set to true in `load_checkpoint_in_model` (see [#5892](https://github.com/NVIDIA/TensorRT-LLM/issues/5892) ), but it also suffers from long execution time (I loaded the full model on 1 node and it took 3 hours to went through the pipeline and start loading weights). Verified that 4 layers can run e2e.
`/bot [-h] …
=> feat:[AutoDeploy] Support Quantized MoE matcher - Step1

tensorrt_llm/_torch/auto_deploy/custom_ops/attention_interface.py, tensorrt_llm/_torch/auto_deploy/llm_args.py, tensorrt_llm/_torch/auto_deploy/shim/ad_executor.py
Add support for overlap scheduler in AD. Fixes issue https://github.com/NVIDIA/TensorRT-LLM/issues/4364
=> fix overlap scheduler in AD

tensorrt_llm/_torch/auto_deploy/config/default.yaml, tensorrt_llm/_torch/auto_deploy/transform/interface.py, tensorrt_llm/_torch/auto_deploy/transform/library/build_model.py, tensorrt_llm/_torch/auto_deploy/transform/library/cleanup_checks.py, tensorrt_llm/_torch/auto_deploy/transform/library/cleanup_noop_add.py, tensorrt_llm/_torch/auto_deploy/transform/library/cleanup_noop_slice.py, tensorrt_llm/_torch/auto_deploy/transform/library/export_to_gm.py, tensorrt_llm/_torch/auto_deploy/transform/optimizer.py, tensorrt_llm/_torch/auto_deploy/transformations/export.py, tests/unittest/_torch/auto_deploy/_utils_test/_graph_test_helpers.py, tests/unittest/_torch/auto_deploy/unit/singlegpu/transformations/library/test_attention_matcher.py, tests/unittest/_torch/auto_deploy/unit/singlegpu/transformations/library/test_kv_cache.py
moving more transforms into the modular inference optimizer
=> [AutoDeploy][2/n] Modular InferenceOptimizer 

tensorrt_llm/_torch/auto_deploy/transformations/_graph.py, tensorrt_llm/_torch/auto_deploy/transformations/library/attention.py, tensorrt_llm/_torch/auto_deploy/transformations/transform.py, tensorrt_llm/_torch/auto_deploy/utils/pattern_matcher.py, tests/unittest/_torch/auto_deploy/unit/singlegpu/transformations/library/test_attention_matcher.py, tests/unittest/_torch/auto_deploy/unit/singlegpu/transformations/library/test_attention_matcher_hf.py
Use torch._inductor pattern matcher to match attention
<details>
`run  [--disable-fail-fast --skip-test --stage-list "A10-1, xxx" --gpu-type "A30, H100_PCIe" --add-multi-gpu-test --only-multi-gpu-test --disable-multi-gpu-test --post-merge --extra-stage "H100_PCIe-[Post-Merge]-1, xxx"]`
Launch build/test pipelines. All previously running jobs will be killed.
`--disable-fail-fast ` *(OPTIONAL)* : Disable fail fast on build/tests/infra failures.
`--skip-test ` *(OPTIONAL)* : Skip all test stages, but still run build stages, package stages and sanity check …
=> Attention Pattern Matcher (closes #4404)

tensorrt_llm/_torch/auto_deploy/models/hf.py
<details>
`run  [--reuse-test (optional)pipeline-id --disable-fail-fast --skip-test --stage-list "A10-PyTorch-1, xxx" --gpu-type "A30, H100_PCIe" --test-backend "pytorch, cpp" --add-multi-gpu-test --only-multi-gpu-test --disable-multi-gpu-test --post-merge --extra-stage "H100_PCIe-TensorRT-Post-Merge-1, xxx" --detailed-log --debug(experimental)]`
Launch build/test pipelines. All previously running jobs will be killed.
`--reuse-test (optional)pipeline-id ` *(OPTIONAL)* : Allow the new pipeline to reuse build artifacts and skip …
=> respect max_seq_len setting for pos embeddings

tests/unittest/_torch/auto_deploy/_utils_test/_graph_test_helpers.py
For issue #98, we want to move tranforms and test cases. This PR update helper function that new test cases depends on. We separate this into an individual PR so that following PRs are independent to each other.
<details>
`run  [--reuse-test (optional)pipeline-id --disable-fail-fast --skip-test --stage-list "A10-PyTorch-1, xxx" --gpu-type "A30, H100_PCIe" --test-backend "pytorch, cpp" --add-multi-gpu-test --only-multi-gpu-test --disable-multi-gpu-test --post-merge --extra-stage "H100_PCIe-TensorRT-Post-Merge-1, xxx" --detailed-log …
=> Update graph test helper for unit tests on new infrencde 

tensorrt_llm/_torch/auto_deploy/transformations/_graph.py, tensorrt_llm/_torch/auto_deploy/transformations/library/attention.py, tensorrt_llm/_torch/auto_deploy/transformations/transform.py, tensorrt_llm/_torch/auto_deploy/utils/pattern_matcher.py, tests/unittest/_torch/auto_deploy/unit/singlegpu/transformations/library/test_attention_matcher.py, tests/unittest/_torch/auto_deploy/unit/singlegpu/transformations/library/test_attention_matcher_hf.py
Perf comparison:
**TP=1**
**Before:**
```
Request Throughput (req/sec):                     21.8243
Total Output Throughput (tokens/sec):             2793.5093
Total Token Throughput (tokens/sec):              5587.0186
Total Latency (ms):                               45820.5022
Average request latency (ms):                     35422.4192
Per User Output Throughput [w/ ctx] (tps/user):   3.9171
Per GPU Output Throughput (tps/gpu):              2793.5093
-- Request Latency Breakdown (ms) -----------------------
[Latency] P50    : 33081.3765
[Latency] P90    : 45524.0860
[Latency] P95    : 45632.3470
[Latency] P99    : 45701.6415
[Latency] MINIMUM: 20661.4764
[Latency] MAXIMUM: 45723.5925
[Latency] AVERAGE: 35422.4192
```
**After:**
```
Request Throughput (req/sec): …
```
=> [Reopen #88]Attention Pattern Matcher with torch._inductor pattern matcher

tensorrt_llm/_torch/auto_deploy/config/default.yaml, tensorrt_llm/_torch/auto_deploy/transform/library/attention.py, tensorrt_llm/_torch/auto_deploy/transformations/library/__init__.py, tensorrt_llm/_torch/auto_deploy/transformations/transform.py, tests/unittest/_torch/auto_deploy/unit/singlegpu/transformations/library/test_attention_matcher.py, tests/unittest/_torch/auto_deploy/unit/singlegpu/transformations/library/test_attention_matcher_hf.py
#98 
- Unite tests passed;
- Trt-bench:  
with modification, tp=1:
```
Request Throughput (req/sec):                     39.0233
Total Output Throughput (tokens/sec):             4994.9836
Total Token Throughput (tokens/sec):              9989.9672
Total Latency (ms):                               25625.7099
Average request latency (ms):                     19997.5614
Per User Output Throughput [w/ ctx] (tps/user):   6.9144
Per GPU Output Throughput (tps/gpu):              4994.9836
```
target branch, tp1=:
```
Request Throughput (req/sec):                     38.3011
Total Output Throughput (tokens/sec):             4902.5367
Total Token Throughput (tokens/sec):              9805.0735
Total Latency (ms):                               26108.9324
Average request …
```
=> Move attention transforms to new inference optimizer

examples/auto_deploy/build_and_run_ad.py, tensorrt_llm/_torch/auto_deploy/compile/backends/torch_compile.py, tensorrt_llm/_torch/auto_deploy/compile/backends/torch_cudagraph.py, tensorrt_llm/_torch/auto_deploy/compile/backends/torch_opt.py, tests/unittest/_torch/auto_deploy/unit/singlegpu/test_ad_trtllm_bench.py
torch._dynamo.config.recompile_limit was not set, so the default value 8 was used, sometimes leading to eager execution.
This change sets it based on the len(cuda_graph_batch_sizes).
Additionally, moved the cuda_graph_batch_sizes calculation (if not set by the user) heuristic to TorchCudagraphCompiler,
have it be a mandatory param to CapturedGraph and removed max_batch_size param (because it is now inferred from cuda_graph_batch_sizes).
Also, moved cache_size_limit from build_and_run_ad.py to the torch-opt and torch-compile BEs.
Added all 3 backends to the test_trtllm_bench and extended the cuda_graph_batch_sizes because cuda graph asserts in small batch size and also it compares it to the input shape batch dim.
tested perf impact, perf is not impacted:
python3 …
=> TRTLLM-6142: set torch recompile_limit based on cuda_graph_batch_sizes and refactored

tensorrt_llm/_torch/auto_deploy/config/default.yaml, tensorrt_llm/_torch/auto_deploy/models/factory.py, tensorrt_llm/_torch/auto_deploy/models/hf.py, tensorrt_llm/_torch/auto_deploy/models/quant_config_reader.py, tensorrt_llm/_torch/auto_deploy/transform/library/quantization.py, tensorrt_llm/_torch/auto_deploy/transformations/transform.py, tests/unittest/_torch/auto_deploy/unit/singlegpu/transformations/library/test_quantization.py
- Unit tests
- E2E tested FP8 models: config based, graph based, Moe(Mixtral), BMM(llama4)
- Perf results:
**Before:**
TP=1
```
Request Throughput (req/sec):                     6.9926
Total Output Throughput (tokens/sec):             895.0499
Total Token Throughput (tokens/sec):              1790.0999
Total Latency (ms):                               143008.7812
Average request latency (ms):                     75925.5988
Per User Output Throughput [w/ ctx] (tps/user):   2.8372
Per GPU Output Throughput (tps/gpu):              895.0499
```
**After:**
```
Request Throughput (req/sec):                     7.0424
Total Output Throughput (tokens/sec):             901.4267
Total Token Throughput (tokens/sec):              1802.8533
Total Latency (ms): …
```
=> [None][autodeploy] Add quantization_source to factory interface

tests/unittest/_torch/auto_deploy/_utils_test/_model_test_utils.py, tests/unittest/_torch/auto_deploy/unit/singlegpu/models/test_bamba.py
minituarized bamba test to stabilize parallel test execution
=> small bamba test for parallel execution

tests/unittest/_torch/auto_deploy/unit/singlegpu/transformations/library/test_attention_matcher.py
Please review the following before submitting your PR:
- PR description clearly explains what and why. If using CodeRabbit's summary, please make sure it makes sense.
- PR Follows [TRT-LLM CODING GUIDELINES](https://github.com/NVIDIA/TensorRT-LLM/blob/main/CODING_GUIDELINES.md) to the best of your knowledge.
- Test cases are provided for new code paths (see [test instructions](https://github.com/NVIDIA/TensorRT-LLM/tree/main/tests#1-how-does-the-ci-work))
- Any new dependencies have been scanned for license and vulnerabilities
- [CODEOWNERS](https://github.com/NVIDIA/TensorRT-LLM/blob/main/.github/CODEOWNERS) updated if ownership changes
- Documentation updated as needed
- The reviewers assigned automatically/manually are appropriate for the PR.
`/bot [-h] ['run', …
=> [None][fix] Fix test_match_attention_layout

tensorrt_llm/_torch/auto_deploy/custom_ops/attention_interface.py
=> fix overflow expression for number of pages in sequence interface
